자동차 경주 게임 구현
biforest/java-racingcar pull request #5
Opened 2021-03-11 19:00 UTC by Jummi10

2021-03-13 11:01 UTC, songpang reviewed
코드 작성하느라 정말 고생많으셨습니다 !

2021-03-13 11:01 UTC, songpang commented on README.md
> +### 기능 목록
리뷰가 늦어 죄송합니다. README를 저번 스터디 때 말씀해 주신 걸 제대로 적용하셔서 굉장히 깔끔해 보이네요! 고생 많으셨습니다 :)

2021-03-13 11:01 UTC, songpang commented on src/main/java/domain/Car.java
> +    private void validateName() {
name을 받아서 에러를 던져주는 곳인 것 같은데 에러가 발생했을 때 처리하는 프로세스를 따로 만들지 않은 이유가 있으신가요? 의도치 않은 입력값에 대한 에러를 처리하는 프로세스를 만드셨으면 더 좋았을 것 같아요!

2021-03-13 11:01 UTC, songpang commented on src/main/java/Application.java
> +        Receiver receiver = new Receiver();
Receiver 클래스에 receiveCarNames()  receiveRound() getCarNames() getRound() 4개의 함수로 분리해 놓으셨는데 굳이 static으로 만들어 함수의 개수를 줄이지 않고 4개를 만드신 이유가 있으신가요?

2021-03-13 11:01 UTC, songpang commented on src/main/java/domain/CarFactory.java
> +        String s = input.replaceAll(BLANK, "");
""만 변수 설정을 따로 안하신 이유가 있을까요? (빈 공백처리를 이런식으로 간단히 할 수 있었군요 !)

2021-03-13 11:01 UTC, songpang commented on src/main/java/domain/RacingCarGame.java
> +        if (randomValue >= 4) {
4같은 경우도 변수로 관리하면 이점이 있을 것 같은데 따로 변수를 만들지 않고 바로 넣으신 이유가 있을까요?

2021-03-13 11:01 UTC, songpang commented on src/main/java/domain/RacingCarGame.java
> +    private void printCurrentPositions() {
현재 위치를 출력하는 함수 안에 print관련 메소드를 사용하는 곳에 4곳이나 되네요! 결과물을 보면 왜 쓰셨는지 이해가 가지만 저에게는 처음에 읽을 때 한 눈에 들어오지 않았어요. 굳이 이렇게 사용하신 이유는 속도 때문이신가요?

2021-03-13 11:01 UTC, songpang commented on src/main/java/domain/exception/NotBlankException.java
> +public class NotBlankException extends IllegalArgumentException {
이 클래스만 따로 만들어 주신 이유가 무엇인가요?

2021-03-13 11:01 UTC, songpang commented on src/main/java/utils/RandomUtils.java
> +    public static int nextInt(final int startInclusive, final int endInclusive) {
nextInt(num)을 이용하면 0부터 num-1까지의 수를 랜덤하게 가져온다고 들었습니다. 굳이 이를 이용하시지 않고 새로 정의하신 이유는 이후의 확장성을 생각하신 건가요?

2021-03-13 11:01 UTC, songpang commented on src/test/java/domain/RacingCarGameTest.java
> +        racingCarGame.proceedRounds();
테스트 중 이부분이 잘 이해가 되지 않았어요. racingCarGame.proceedRounds(); 이 한 줄로 어떻게 테스트를 하는 건가요?

2021-03-13 11:01 UTC, songpang commented on src/test/java/domain/RacingCarGameTest.java
> +        racingCarGame.printWinners();
이부분도 마찬가지로 이해가 되지 않아요. 이렇게 테스트를 하는 방법에 대해 설명해주실 수 있나요?

2021-03-14 09:54 UTC, kouz95 requested changes
고생하셨습니다 👍

리뷰에 덧붙여 오늘 세션에서 진행한 일급컬렉션과, 테스트 가능한 구조로 바꾸는 연습을 해보는것도 좋을 것 같아요 🙂

2021-03-14 09:54 UTC, kouz95 commented on src/main/java/ui/Receiver.java
> +    }
Receiver 아이디어가 재밌네요 ㅋㅋ
`carNames = receiveCarNames()`로 변경해도 좋을것 같아요 🙂

2021-03-14 09:54 UTC, kouz95 commented on src/main/java/domain/CarFactory.java
> +        String s = input.replaceAll(BLANK, "");
`s`는 좀 그렇네요 ㅜㅜ

2021-03-14 09:54 UTC, kouz95 commented on src/main/java/domain/CarFactory.java
> +    private final String[] carNames;
상수와 멤버변수 사이에 공백이 추가되어야합니다 🙂
```suggestion
    public static final String COMMA = ",";
    public static final String BLANK = " ";

    private final List<Car> cars;
    private final String[] carNames;
```

2021-03-14 09:54 UTC, kouz95 commented on src/main/java/domain/CarFactory.java
> +    private final String[] carNames;
CarFactory가 `cars`와 `carNames`를 갖고 있어야할 이유가 있나요?

2021-03-14 09:54 UTC, kouz95 commented on src/main/java/domain/RacingCarGame.java
> +    private final List<Car> cars;
```suggestion
    private static final String DASH = "-";

    private final List<Car> cars;
```

2021-03-14 09:54 UTC, kouz95 commented on src/main/java/domain/RacingCarGame.java
> +    }
[향상된 for문](https://library1008.tistory.com/66) 혹은 stream을 사용한다면 index기반의 접근을 안할 수도 있을 것 같아요 🙂

2021-03-14 09:54 UTC, kouz95 commented on src/main/java/domain/RacingCarGame.java
> +        Collections.sort(cars);
sort를 시켜버리게 되면 원본의 cars가 훼손되는 일이 일어나겠군요 😥

2021-03-28 11:49 UTC, Jummi10 commented
일급컬렉션을 적용하다보니 `Cars` 클래스가 너무 뚱뚱해졌나 생각도 들긴 한데 `Cars.findWinners()`와 `Cars.getMaxPosition()`을 `RacingCarGame` 클래스에서 하게되면 
```java
    private final Cars cars;
    public Cars chooseWinners() {
        int maxPosition = cars.getCars().stream()
            .max((Comparator.comparingInt(Car::getPosition)))
            .orElseThrow(IllegalArgumentException::new)
            .getPosition();

        return winners = cars.getCars().stream()
            .~~;
    }
```
이런 식으로 `cars.getCars()`를 하게 되어 일급컬렉션을 쓰는 의미가 없어지는것 같아 일단 Cars에게 책임을 다 넘겼습니다

또한 `Cars.toStringCurrentPositions()`와 `Cars.toStringWinners()`도 `Car.toString()`와 비슷한 맥락으로, 각각 차 하나의 position을 스트링으로, 차들의 포지션들을 스트링으로 바꾸고자 해서 Printer에 로직을 넣지 않고 Cars 클래스에 넣게 되었습니다

일급 컬렉션을 처음 써봐서 이렇게 하는 것이 맞나 궁금한데 한 번 봐주시면 좋겠습니다 감사합니다 :)

2021-03-29 11:30 UTC, kouz95 requested changes
추가적인 리뷰 남겼으니 확인해주세요 🙏

2021-03-29 11:30 UTC, kouz95 commented on src/main/java/domain/RacingCarGame.java
> +    private Cars winners;
winners를 인스턴스 변수로 갖지 않아도 동작할 수 있을것 같네요 🙂

![image](https://user-images.githubusercontent.com/52931057/112829596-4c22a880-90cc-11eb-9b85-b6130161964f.png)

2021-03-29 11:30 UTC, kouz95 commented on src/main/java/domain/Cars.java
> +            .filter(car -> car.getPosition() == maxPosition)
car에게 메세지를 던져서 포지션이 같은지 확인할 수 있지 않을까요?

2021-03-29 11:30 UTC, kouz95 commented on src/main/java/domain/Cars.java
> +    }
Car에 뷰로직이 존재하는것 같아요. 
비지니스 로직과 뷰 로직을 분리해야하는 이유는 무엇일까요? 🤔

2021-03-29 11:30 UTC, kouz95 commented on src/main/java/domain/Car.java
> +    }
toString을 Override할땐 `toString()`이 객체의 참조 값을 반환하는 것이 아닌, 객체의 상태를 반환하는 것이 용이하다고 판단 될때 입니다.

```java
    @Override
    public String toString() {
        return "Car{" +
                "name=" + name +
                ", position=" + position +
                '}';
    }
```
물론, `System.out.println(car);` 만으로 해결되는 것이 매력적이긴 하겠지만, ui와 강한 결합을 갖게 됩니다.
`a : ---` 는 자동차의 이름과 위치를 표현하기 위한 ui의 정책이지 않나요?

2021-03-29 11:30 UTC, kouz95 commented on src/main/java/domain/Car.java
> +            position += 1;
1도 상수화할 수 있지 않을까요?

2021-03-30 07:34 UTC, kouz95 approved these changes
고생하셨습니다 👍

2021-03-30 07:34 UTC, merged